# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
#  dockerRegistryServiceConnection: 'a84bfb04-c385-4f18-bc96-015265fc800e'
#  imageRepository: 'azurevote'
#  containerRegistry: 'oneillalacr.azurecr.io'
#  dockerfilePath: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
#  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Provision AKS
  displayName: Provision an aks cluster
  jobs:  
  - job: AKS
    displayName: AKS
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo Provisioning cluster
        az aks create --resource-group  k8s-resource-group --name eadAKSCluster --node-count 1 --location westeurope --service-principal 9baf5ccd-bb5c-4bf3-bce0-9c23748d2e2d --client-secret 9baf5ccd-bb5c-4bf3-bce0-9c23748d2e2d --generate-ssh-keys
      displayName: 'Provision aks cluster'
